### ISSUE TITLE
会签、或签节点都会报错

### ISSUE THREAD

**Issue by zhuhongguang** [KonBAI-Q/RuoYi-Flowable-Plus#3]
会签或签功能不能用吗

**Comment by KonBAI-Q** [comment]
可能会存在一些bug，能详细说明一下，你遇到的什么问题吗？

**Comment by zhuhongguang** [comment]
> 可能会存在一些bug，能详细说明一下，你遇到的什么问题吗？

某个节点设置为角色或者部门时，指定2个以上的人，启动流程报错。
