### ISSUE TITLE
几个小问题。

### ISSUE THREAD

**Issue by MarsZone** [KonBAI-Q/RuoYi-Flowable-Plus#5]
作者大佬，这个后续改造接入Cloud麻烦么。
另外
工作流模块流程表单移除 form-generator 组件改用 vform 表单
vform比form-generator 更好用么。
如果先用了0.8.x版本，后面升级9.0好升不

**Comment by MarsZone** [comment]
项目还有继续维护开发的计划么。

**Comment by KonBAI-Q** [comment]
0.8和0.9不兼容，升级会比较麻烦。现在0.9版本功能还不完善。vform比form-generator 功能更丰富。
